### ISSUE TITLE
改造成微服务有进展吗

### ISSUE THREAD

**Issue by zinwalin** [YHWL/accbase#1]
难度大吗？

**Comment by winyh** [comment]
> 难度大吗？

不难，我大概说下思路，你可以自己尝试实现下。

1.首先你需要了解 微服务概念，我准备用 go micro 这个微服务框架做这个事情，其次是 需要了解 casbin 这个库

2.微服务改造就是基于这两个来整合 casbin 的 API 对外提供服务的

**Comment by zinwalin** [comment]
> > 难度大吗？
> 
> 不难，我大概说下思路，你可以自己尝试实现下。
> 
> 1.首先你需要了解 微服务概念，我准备用 go micro 这个微服务框架做这个事情，其次是 需要了解 casbin 这个库
> 
> 2.微服务改造就是基于这两个来整合 casbin 的 API 对外提供服务的

微服务会碰到跨域问题吧? 一般是什么思路？

**Comment by winyh** [comment]
> > > 难度大吗？
> > 
> > 
> > 不难，我大概说下思路，你可以自己尝试实现下。
> > 1.首先你需要了解 微服务概念，我准备用 go micro 这个微服务框架做这个事情，其次是 需要了解 casbin 这个库
> > 2.微服务改造就是基于这两个来整合 casbin 的 API 对外提供服务的
> 
> 微服务会碰到跨域问题吧? 一般是什么思路？

微服务之间相互调用不会存在跨域的，出现跨域是浏览器的限制。浏览器跨域可以通过 后台设置 cors 来处理

**Comment by winyh** [comment]
> 难度大吗？

改造进行中...已完成用户注册登录和通过token 获取用户信息的功能.
